/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IBountyEscrow, IBountyEscrowInterface } from "../../interfaces/IBountyEscrow.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "bountyId",
        "type": "bytes32"
      }
    ],
    "name": "getBounty",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "maintainer",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "token",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "recipient",
            "type": "address"
          },
          {
            "internalType": "uint128",
            "name": "amount",
            "type": "uint128"
          },
          {
            "internalType": "uint64",
            "name": "expiresAt",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "releaseAt",
            "type": "uint64"
          },
          {
            "internalType": "enum IBountyEscrow.BountyStatus",
            "name": "status",
            "type": "uint8"
          }
        ],
        "internalType": "struct IBountyEscrow.Bounty",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "bountyId",
        "type": "bytes32"
      }
    ],
    "name": "markDisputed",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "bountyId",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "recipient",
        "type": "address"
      },
      {
        "internalType": "uint64",
        "name": "releaseAt",
        "type": "uint64"
      }
    ],
    "name": "recordVerdict",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "bountyId",
        "type": "bytes32"
      }
    ],
    "name": "resolveDisputeToMaintainer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "bountyId",
        "type": "bytes32"
      }
    ],
    "name": "resolveDisputeToRecipient",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IBountyEscrow__factory {
    static readonly abi = _abi;
    static createInterface(): IBountyEscrowInterface {
      return new Interface(_abi) as IBountyEscrowInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IBountyEscrow {
      return new Contract(address, _abi, runner) as unknown as IBountyEscrow;
    }
  }
  