/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IVerdictRegistry, IVerdictRegistryInterface } from "../../interfaces/IVerdictRegistry.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "bountyId",
        "type": "bytes32"
      }
    ],
    "name": "getVerdict",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "evidenceHash",
            "type": "bytes32"
          },
          {
            "internalType": "string",
            "name": "evidenceCid",
            "type": "string"
          },
          {
            "internalType": "address",
            "name": "recipient",
            "type": "address"
          },
          {
            "internalType": "uint16",
            "name": "finalScoreBps",
            "type": "uint16"
          },
          {
            "internalType": "uint64",
            "name": "submittedAt",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "challengeEndsAt",
            "type": "uint64"
          },
          {
            "internalType": "bool",
            "name": "exists",
            "type": "bool"
          }
        ],
        "internalType": "struct IVerdictRegistry.Verdict",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IVerdictRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): IVerdictRegistryInterface {
      return new Interface(_abi) as IVerdictRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IVerdictRegistry {
      return new Contract(address, _abi, runner) as unknown as IVerdictRegistry;
    }
  }
  