/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace IBountyEscrow {
      
    export type BountyStruct = {maintainer: AddressLike, token: AddressLike, recipient: AddressLike, amount: BigNumberish, expiresAt: BigNumberish, releaseAt: BigNumberish, status: BigNumberish}

    export type BountyStructOutput = [maintainer: string, token: string, recipient: string, amount: bigint, expiresAt: bigint, releaseAt: bigint, status: bigint] & {maintainer: string, token: string, recipient: string, amount: bigint, expiresAt: bigint, releaseAt: bigint, status: bigint }
  
    }

  export interface BountyEscrowInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "DISPUTE_MANAGER_ROLE" | "VERDICT_REGISTRY_ROLE" | "cancelOpenBounty" | "createBounty" | "defaultRewardToken" | "getBounty" | "getRoleAdmin" | "grantRole" | "hasRole" | "markDisputed" | "pause" | "paused" | "recordVerdict" | "refundExpiredBounty" | "releaseBounty" | "renounceRole" | "resolveDisputeToMaintainer" | "resolveDisputeToRecipient" | "revokeRole" | "setDefaultRewardToken" | "supportsInterface" | "unpause"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BountyChallenged" | "BountyCreated" | "BountyPaid" | "BountyRefunded" | "DefaultTokenUpdated" | "Paused" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Unpaused" | "VerdictRecorded"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DISPUTE_MANAGER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'VERDICT_REGISTRY_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancelOpenBounty', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'createBounty', values: [BytesLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'defaultRewardToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBounty', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'markDisputed', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordVerdict', values: [BytesLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'refundExpiredBounty', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'releaseBounty', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'resolveDisputeToMaintainer', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'resolveDisputeToRecipient', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setDefaultRewardToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DISPUTE_MANAGER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'VERDICT_REGISTRY_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelOpenBounty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createBounty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'defaultRewardToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBounty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markDisputed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordVerdict', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundExpiredBounty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseBounty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDisputeToMaintainer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDisputeToRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDefaultRewardToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
  }

  
    export namespace BountyChallengedEvent {
      export type InputTuple = [bountyId: BytesLike];
      export type OutputTuple = [bountyId: string];
      export interface OutputObject {bountyId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BountyCreatedEvent {
      export type InputTuple = [bountyId: BytesLike, maintainer: AddressLike, token: AddressLike, amount: BigNumberish, expiresAt: BigNumberish];
      export type OutputTuple = [bountyId: string, maintainer: string, token: string, amount: bigint, expiresAt: bigint];
      export interface OutputObject {bountyId: string, maintainer: string, token: string, amount: bigint, expiresAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BountyPaidEvent {
      export type InputTuple = [bountyId: BytesLike, recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [bountyId: string, recipient: string, amount: bigint];
      export interface OutputObject {bountyId: string, recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BountyRefundedEvent {
      export type InputTuple = [bountyId: BytesLike, maintainer: AddressLike, amount: BigNumberish, status: BigNumberish];
      export type OutputTuple = [bountyId: string, maintainer: string, amount: bigint, status: bigint];
      export interface OutputObject {bountyId: string, maintainer: string, amount: bigint, status: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DefaultTokenUpdatedEvent {
      export type InputTuple = [previousToken: AddressLike, newToken: AddressLike];
      export type OutputTuple = [previousToken: string, newToken: string];
      export interface OutputObject {previousToken: string, newToken: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VerdictRecordedEvent {
      export type InputTuple = [bountyId: BytesLike, recipient: AddressLike, releaseAt: BigNumberish];
      export type OutputTuple = [bountyId: string, recipient: string, releaseAt: bigint];
      export interface OutputObject {bountyId: string, recipient: string, releaseAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BountyEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): BountyEscrow;
    waitForDeployment(): Promise<this>;

    interface: BountyEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DISPUTE_MANAGER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    VERDICT_REGISTRY_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    cancelOpenBounty: TypedContractMethod<
      [bountyId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    createBounty: TypedContractMethod<
      [bountyId: BytesLike, token: AddressLike, amount: BigNumberish, expiresAt: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    defaultRewardToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getBounty: TypedContractMethod<
      [bountyId: BytesLike, ],
      [IBountyEscrow.BountyStructOutput],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    markDisputed: TypedContractMethod<
      [bountyId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    recordVerdict: TypedContractMethod<
      [bountyId: BytesLike, recipient: AddressLike, releaseAt: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    refundExpiredBounty: TypedContractMethod<
      [bountyId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    releaseBounty: TypedContractMethod<
      [bountyId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    resolveDisputeToMaintainer: TypedContractMethod<
      [bountyId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    resolveDisputeToRecipient: TypedContractMethod<
      [bountyId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setDefaultRewardToken: TypedContractMethod<
      [newToken: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DISPUTE_MANAGER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'VERDICT_REGISTRY_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cancelOpenBounty'): TypedContractMethod<
      [bountyId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createBounty'): TypedContractMethod<
      [bountyId: BytesLike, token: AddressLike, amount: BigNumberish, expiresAt: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'defaultRewardToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getBounty'): TypedContractMethod<
      [bountyId: BytesLike, ],
      [IBountyEscrow.BountyStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'markDisputed'): TypedContractMethod<
      [bountyId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'recordVerdict'): TypedContractMethod<
      [bountyId: BytesLike, recipient: AddressLike, releaseAt: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'refundExpiredBounty'): TypedContractMethod<
      [bountyId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseBounty'): TypedContractMethod<
      [bountyId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDisputeToMaintainer'): TypedContractMethod<
      [bountyId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDisputeToRecipient'): TypedContractMethod<
      [bountyId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDefaultRewardToken'): TypedContractMethod<
      [newToken: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BountyChallenged'): TypedContractEvent<BountyChallengedEvent.InputTuple, BountyChallengedEvent.OutputTuple, BountyChallengedEvent.OutputObject>;
getEvent(key: 'BountyCreated'): TypedContractEvent<BountyCreatedEvent.InputTuple, BountyCreatedEvent.OutputTuple, BountyCreatedEvent.OutputObject>;
getEvent(key: 'BountyPaid'): TypedContractEvent<BountyPaidEvent.InputTuple, BountyPaidEvent.OutputTuple, BountyPaidEvent.OutputObject>;
getEvent(key: 'BountyRefunded'): TypedContractEvent<BountyRefundedEvent.InputTuple, BountyRefundedEvent.OutputTuple, BountyRefundedEvent.OutputObject>;
getEvent(key: 'DefaultTokenUpdated'): TypedContractEvent<DefaultTokenUpdatedEvent.InputTuple, DefaultTokenUpdatedEvent.OutputTuple, DefaultTokenUpdatedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'VerdictRecorded'): TypedContractEvent<VerdictRecordedEvent.InputTuple, VerdictRecordedEvent.OutputTuple, VerdictRecordedEvent.OutputObject>;

    filters: {
      
      'BountyChallenged(bytes32)': TypedContractEvent<BountyChallengedEvent.InputTuple, BountyChallengedEvent.OutputTuple, BountyChallengedEvent.OutputObject>;
      BountyChallenged: TypedContractEvent<BountyChallengedEvent.InputTuple, BountyChallengedEvent.OutputTuple, BountyChallengedEvent.OutputObject>;
    

      'BountyCreated(bytes32,address,address,uint256,uint64)': TypedContractEvent<BountyCreatedEvent.InputTuple, BountyCreatedEvent.OutputTuple, BountyCreatedEvent.OutputObject>;
      BountyCreated: TypedContractEvent<BountyCreatedEvent.InputTuple, BountyCreatedEvent.OutputTuple, BountyCreatedEvent.OutputObject>;
    

      'BountyPaid(bytes32,address,uint256)': TypedContractEvent<BountyPaidEvent.InputTuple, BountyPaidEvent.OutputTuple, BountyPaidEvent.OutputObject>;
      BountyPaid: TypedContractEvent<BountyPaidEvent.InputTuple, BountyPaidEvent.OutputTuple, BountyPaidEvent.OutputObject>;
    

      'BountyRefunded(bytes32,address,uint256,uint8)': TypedContractEvent<BountyRefundedEvent.InputTuple, BountyRefundedEvent.OutputTuple, BountyRefundedEvent.OutputObject>;
      BountyRefunded: TypedContractEvent<BountyRefundedEvent.InputTuple, BountyRefundedEvent.OutputTuple, BountyRefundedEvent.OutputObject>;
    

      'DefaultTokenUpdated(address,address)': TypedContractEvent<DefaultTokenUpdatedEvent.InputTuple, DefaultTokenUpdatedEvent.OutputTuple, DefaultTokenUpdatedEvent.OutputObject>;
      DefaultTokenUpdated: TypedContractEvent<DefaultTokenUpdatedEvent.InputTuple, DefaultTokenUpdatedEvent.OutputTuple, DefaultTokenUpdatedEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'VerdictRecorded(bytes32,address,uint64)': TypedContractEvent<VerdictRecordedEvent.InputTuple, VerdictRecordedEvent.OutputTuple, VerdictRecordedEvent.OutputObject>;
      VerdictRecorded: TypedContractEvent<VerdictRecordedEvent.InputTuple, VerdictRecordedEvent.OutputTuple, VerdictRecordedEvent.OutputObject>;
    
    };
  }