/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace IVerdictRegistry {
      
    export type VerdictStruct = {evidenceHash: BytesLike, evidenceCid: string, recipient: AddressLike, finalScoreBps: BigNumberish, submittedAt: BigNumberish, challengeEndsAt: BigNumberish, exists: boolean}

    export type VerdictStructOutput = [evidenceHash: string, evidenceCid: string, recipient: string, finalScoreBps: bigint, submittedAt: bigint, challengeEndsAt: bigint, exists: boolean] & {evidenceHash: string, evidenceCid: string, recipient: string, finalScoreBps: bigint, submittedAt: bigint, challengeEndsAt: bigint, exists: boolean }
  
    }

  export interface VerdictRegistryInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "MAX_SCORE_BPS" | "RELAYER_ROLE" | "challengePeriod" | "escrow" | "getRoleAdmin" | "getVerdict" | "grantRole" | "hasRole" | "minimumPassingScoreBps" | "pause" | "paused" | "renounceRole" | "revokeRole" | "setChallengePeriod" | "setMinimumPassingScoreBps" | "submitVerdict" | "supportsInterface" | "unpause"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ChallengePeriodUpdated" | "MinimumPassingScoreUpdated" | "Paused" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Unpaused" | "VerdictSubmitted"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_SCORE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'RELAYER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'challengePeriod', values?: undefined): string;
encodeFunctionData(functionFragment: 'escrow', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getVerdict', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'minimumPassingScoreBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setChallengePeriod', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setMinimumPassingScoreBps', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitVerdict', values: [BytesLike, BytesLike, string, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_SCORE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'RELAYER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'challengePeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVerdict', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minimumPassingScoreBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setChallengePeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMinimumPassingScoreBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitVerdict', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
  }

  
    export namespace ChallengePeriodUpdatedEvent {
      export type InputTuple = [previousPeriod: BigNumberish, newPeriod: BigNumberish];
      export type OutputTuple = [previousPeriod: bigint, newPeriod: bigint];
      export interface OutputObject {previousPeriod: bigint, newPeriod: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MinimumPassingScoreUpdatedEvent {
      export type InputTuple = [previousScore: BigNumberish, newScore: BigNumberish];
      export type OutputTuple = [previousScore: bigint, newScore: bigint];
      export interface OutputObject {previousScore: bigint, newScore: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VerdictSubmittedEvent {
      export type InputTuple = [bountyId: BytesLike, evidenceHash: BytesLike, recipient: AddressLike, evidenceCid: string, finalScoreBps: BigNumberish, challengeEndsAt: BigNumberish];
      export type OutputTuple = [bountyId: string, evidenceHash: string, recipient: string, evidenceCid: string, finalScoreBps: bigint, challengeEndsAt: bigint];
      export interface OutputObject {bountyId: string, evidenceHash: string, recipient: string, evidenceCid: string, finalScoreBps: bigint, challengeEndsAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface VerdictRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): VerdictRegistry;
    waitForDeployment(): Promise<this>;

    interface: VerdictRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    MAX_SCORE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    RELAYER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    challengePeriod: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    escrow: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getVerdict: TypedContractMethod<
      [bountyId: BytesLike, ],
      [IVerdictRegistry.VerdictStructOutput],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    minimumPassingScoreBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setChallengePeriod: TypedContractMethod<
      [newPeriod: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setMinimumPassingScoreBps: TypedContractMethod<
      [newScore: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submitVerdict: TypedContractMethod<
      [bountyId: BytesLike, evidenceHash: BytesLike, evidenceCid: string, recipient: AddressLike, finalScoreBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_SCORE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'RELAYER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'challengePeriod'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'escrow'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getVerdict'): TypedContractMethod<
      [bountyId: BytesLike, ],
      [IVerdictRegistry.VerdictStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'minimumPassingScoreBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setChallengePeriod'): TypedContractMethod<
      [newPeriod: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMinimumPassingScoreBps'): TypedContractMethod<
      [newScore: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitVerdict'): TypedContractMethod<
      [bountyId: BytesLike, evidenceHash: BytesLike, evidenceCid: string, recipient: AddressLike, finalScoreBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ChallengePeriodUpdated'): TypedContractEvent<ChallengePeriodUpdatedEvent.InputTuple, ChallengePeriodUpdatedEvent.OutputTuple, ChallengePeriodUpdatedEvent.OutputObject>;
getEvent(key: 'MinimumPassingScoreUpdated'): TypedContractEvent<MinimumPassingScoreUpdatedEvent.InputTuple, MinimumPassingScoreUpdatedEvent.OutputTuple, MinimumPassingScoreUpdatedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'VerdictSubmitted'): TypedContractEvent<VerdictSubmittedEvent.InputTuple, VerdictSubmittedEvent.OutputTuple, VerdictSubmittedEvent.OutputObject>;

    filters: {
      
      'ChallengePeriodUpdated(uint64,uint64)': TypedContractEvent<ChallengePeriodUpdatedEvent.InputTuple, ChallengePeriodUpdatedEvent.OutputTuple, ChallengePeriodUpdatedEvent.OutputObject>;
      ChallengePeriodUpdated: TypedContractEvent<ChallengePeriodUpdatedEvent.InputTuple, ChallengePeriodUpdatedEvent.OutputTuple, ChallengePeriodUpdatedEvent.OutputObject>;
    

      'MinimumPassingScoreUpdated(uint16,uint16)': TypedContractEvent<MinimumPassingScoreUpdatedEvent.InputTuple, MinimumPassingScoreUpdatedEvent.OutputTuple, MinimumPassingScoreUpdatedEvent.OutputObject>;
      MinimumPassingScoreUpdated: TypedContractEvent<MinimumPassingScoreUpdatedEvent.InputTuple, MinimumPassingScoreUpdatedEvent.OutputTuple, MinimumPassingScoreUpdatedEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'VerdictSubmitted(bytes32,bytes32,address,string,uint16,uint64)': TypedContractEvent<VerdictSubmittedEvent.InputTuple, VerdictSubmittedEvent.OutputTuple, VerdictSubmittedEvent.OutputObject>;
      VerdictSubmitted: TypedContractEvent<VerdictSubmittedEvent.InputTuple, VerdictSubmittedEvent.OutputTuple, VerdictSubmittedEvent.OutputObject>;
    
    };
  }