/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IBountyEscrow {
      
    export type BountyStruct = {maintainer: AddressLike, token: AddressLike, recipient: AddressLike, amount: BigNumberish, expiresAt: BigNumberish, releaseAt: BigNumberish, status: BigNumberish}

    export type BountyStructOutput = [maintainer: string, token: string, recipient: string, amount: bigint, expiresAt: bigint, releaseAt: bigint, status: bigint] & {maintainer: string, token: string, recipient: string, amount: bigint, expiresAt: bigint, releaseAt: bigint, status: bigint }
  
    }

  export interface IBountyEscrowInterface extends Interface {
    getFunction(nameOrSignature: "getBounty" | "markDisputed" | "recordVerdict" | "resolveDisputeToMaintainer" | "resolveDisputeToRecipient"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getBounty', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'markDisputed', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'recordVerdict', values: [BytesLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolveDisputeToMaintainer', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'resolveDisputeToRecipient', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'getBounty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markDisputed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordVerdict', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDisputeToMaintainer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDisputeToRecipient', data: BytesLike): Result;
  }

  

  export interface IBountyEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): IBountyEscrow;
    waitForDeployment(): Promise<this>;

    interface: IBountyEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getBounty: TypedContractMethod<
      [bountyId: BytesLike, ],
      [IBountyEscrow.BountyStructOutput],
      'view'
    >
    

    
    markDisputed: TypedContractMethod<
      [bountyId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    recordVerdict: TypedContractMethod<
      [bountyId: BytesLike, recipient: AddressLike, releaseAt: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolveDisputeToMaintainer: TypedContractMethod<
      [bountyId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    resolveDisputeToRecipient: TypedContractMethod<
      [bountyId: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getBounty'): TypedContractMethod<
      [bountyId: BytesLike, ],
      [IBountyEscrow.BountyStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'markDisputed'): TypedContractMethod<
      [bountyId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordVerdict'): TypedContractMethod<
      [bountyId: BytesLike, recipient: AddressLike, releaseAt: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDisputeToMaintainer'): TypedContractMethod<
      [bountyId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDisputeToRecipient'): TypedContractMethod<
      [bountyId: BytesLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }