/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBountyEscrow } from './IBountyEscrow.js';
export type { IVerdictRegistry } from './IVerdictRegistry.js';