/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IVerdictRegistry {
      
    export type VerdictStruct = {evidenceHash: BytesLike, evidenceCid: string, recipient: AddressLike, finalScoreBps: BigNumberish, submittedAt: BigNumberish, challengeEndsAt: BigNumberish, exists: boolean}

    export type VerdictStructOutput = [evidenceHash: string, evidenceCid: string, recipient: string, finalScoreBps: bigint, submittedAt: bigint, challengeEndsAt: bigint, exists: boolean] & {evidenceHash: string, evidenceCid: string, recipient: string, finalScoreBps: bigint, submittedAt: bigint, challengeEndsAt: bigint, exists: boolean }
  
    }

  export interface IVerdictRegistryInterface extends Interface {
    getFunction(nameOrSignature: "getVerdict"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getVerdict', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'getVerdict', data: BytesLike): Result;
  }

  

  export interface IVerdictRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): IVerdictRegistry;
    waitForDeployment(): Promise<this>;

    interface: IVerdictRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getVerdict: TypedContractMethod<
      [bountyId: BytesLike, ],
      [IVerdictRegistry.VerdictStructOutput],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getVerdict'): TypedContractMethod<
      [bountyId: BytesLike, ],
      [IVerdictRegistry.VerdictStructOutput],
      'view'
    >;

    

    filters: {
      
    };
  }